services:
  - type: web
    name: taza-logistics-api
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false

  - type: web
    name: taza-logistics-client
    runtime: static
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
